name: Build macOS Binary

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build project
        run: cargo build --release
        working-directory: ./betterauth_cli
      
      - name: Upload macOS binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: betterauth-cli-macos
          path: betterauth_cli/target/release/betterauth_cli